api/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('user-channels/',views.UserChannelsAPIView.as_view(),name='api-hello-view'),
    path('channel-messages/<channel_id>/', views.ChannelMessagesAPIView.as_view(), name='channel-messages-api'),
    path('channel-details/<id>/', views.ChannelDetailAPIView.as_view(), name='channel-details-api'),
    path("send-message/", views.send_msg_api, name="send-message-api"),
    path('mark-message-as-read/<message_id>/', views.mark_message_read_api, name='mark-message-as-read-api'),
    path('channel-new-messages/<channel_id>/', views.ChannelUnreadMessagesAPIView.as_view(), name='channel-new-messages-api'),  
    path('delete-msg/<message_id>/', views.delete_msg, name='delete-message-api'),
    
]

nexus/nexus/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(django.contrib.auth.urls)),
    path('users/',include('users.urls')),
    path('channels/',include('channels.urls'))
]

nexus/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('channels/',include('channels.urls')),
    path('verify/',include('verify.urls')),
    path('api/',include('api.urls')),
    path('invite/',include('invite.urls')),
    #path('',views.hello,name='nexus-hello-view'),
    path('',RedirectView.as_view(url="/channels/"),name='nexus-hello-view'),
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

verify/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('',RedirectView.as_view(url="/users/login/"),name='empty-verify-view'),
    path('<str:token_to_check>',views.validate_token,name='verify-view'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class NexusUser(AbstractUser):
  # tous les labels sont vides, on n'utilise que les placeholders
  username = models.CharField(max_length = 50, unique = True)
  photo_de_profil = models.ImageField(default='default.jpg', upload_to='user_imgs',null=True,blank=True)
  email = models.EmailField(unique = True)
  is_disabled = models.BooleanField(default=False) # for removing accounts
  # field is_active is for email verification
  
  def __str__(self):
    return f' |{self.username}--{self.email}|'

verify/views.py
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.signing import TimestampSigner,BadSignature,SignatureExpired
from base64 import urlsafe_b64decode
from users.models import NexusUser
from users.views import send_verif_email

email_verification_delay = 2*24*3600 # 2 days (in seconds)
DEST_AFTER_VALIDATION = 'login.html'
DEST_IF_FAILED = 'login.html'

def validate_token(request,token_to_check):
    try:
        user_to_validate = TimestampSigner().unsign_object(urlsafe_b64decode(token_to_check).decode(),max_age=email_verification_delay) #7 jours
        user = get_object_or_404(NexusUser,email=user_to_validate["email"])
        if not user.is_active: # if user hasnt already activated his account
            user.is_active = True
            user.save()
            messages.success(request, 'Votre compte a été vérifié, vous pouvez vous connecter.')
        else:
            messages.error(request, "Votre compte est déjà vérifié !")
        return render(request, DEST_AFTER_VALIDATION)
    except SignatureExpired: # verification link is expired
        user_with_expired_link = TimestampSigner().unsign_object(urlsafe_b64decode(token_to_check).decode(),max_age=360*24*3600) # 360 days,  big enough to always be verified
        user_expired = get_object_or_404(NexusUser,email=user_with_expired_link["email"])
        if not user_expired.is_active: # if user hasnt already activated his account, otherwise we shouldnt resend a new link
            send_verif_email(request,user_with_expired_link["email"])
            messages.error(request, "Ce lien de vérification a expiré, un nouveau a été envoyé à votre adresse e-mail")
        else:
            messages.error(request, "Votre compte est déjà vérifié !")
        return render(request, DEST_IF_FAILED)
    except Exception:
        messages.error(request, "Lien de vérification invalide.")
        return render(request, DEST_IF_FAILED)

templates/account.html

{% extends "base.html" %}
{% load static %}
{% block title %}Nexus - Mon compte{% endblock %}
{% block wrapper %}
    <h1>Mon compte</h1><br/>
    <p>Username : {{ request.user.username }}</p>
    <p>Email : {{ request.user.email }}</p>
    <p>Photo de profil :</p>
    <img src='{{request.user.photo_de_profil.url}}' style="width: 50px; height: 50px;">


    <div class="link"><p><a href="{% url 'account-modify' %}">Modifier le compte</a></p></div>
    <div class="link"><p><a href="/users/account/delete/">Supprimer le compte</a></p></div>
    <div class="link"><p><a href="/channels/">Retour</a></p></div>

{% endblock %}

templates/account_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}Nexus - Suppression de compte{% endblock %}
{% block wrapper %}


<h1>Confirmation de suppression de compte</h1>
<p>Êtes-vous sûr de vouloir supprimer votre compte ?<br/>Cette action est irréversible.</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn">Confirmer la suppression du compte</button>
</form>
<br/><div class="link"><p><a href="/users/account/">Retour</a></p></div>
{% endblock %}

templates/account_modify.html
{% extends "base.html" %}
{% load static %}
{% block title %}Nexus - Modifier mon compte{% endblock %}
{% block wrapper %}
<h1>Modification du compte</h1>
<br/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="id_username">Username :</label><div class="input-box">
    <input type="text" name="username" value="{{ request.user.username }}" autofocus required id="id_username"></div>
    
    <label for="id_email">Email :</label><div class="input-box">
    <input type="email" name="email" value="{{ request.user.email }}" required id="id_email"></div>
    
    <label for="id_photo_de_profil">Photo de profil :</label><div class="input-box">
    <input type="file" name="photo_de_profil" style="padding-top: 11px;" accept="image/*" id="id_photo_de_profil"></div>

    <button type="submit" class="btn">Valider les modifications</button>

</form>
<div class="link"><p><a href="/users/account/">Retour</a></p></div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" , content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block styles %}
    <!-- thème general du site -->
    <link rel="stylesheet" href="{% static  '/styles/style_main.css'%}">
    <!-- css pour pages de login et signup -->
    <link rel="stylesheet" href="{% static  '/styles/style_login.css'%}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/logo/pixel/logo3.png' %}" >


    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
        integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <!-- bootstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- bootstrap js-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <script>
        /* on charge ce css specifiquement si on est dans channels/m/id */
        if (window.location.href.split('/')[3] === 'channels' && window.location.href.split('/')[5]) {
            const cssLink = document.createElement('link');
            cssLink.rel = 'stylesheet';
            cssLink.href = "{% static  '/styles/style_channels.css'%}";

            document.head.appendChild(cssLink);
        } else if (window.location.href.split('/')[3] === 'channels') {
            const cssLink = document.createElement('link');
            cssLink.rel = 'stylesheet';
            cssLink.href = "{% static  '/styles/style_homepage.css'%}";

            document.head.appendChild(cssLink);
        }

    </script>

    {% endblock %}

    {% block extra_css %} {% endblock %}

    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    {% if request.user.is_authenticated %}
    <div class="position-absolute top-0 end-0">
        <div class="dropdown mx-auto" style="max-width: 500px;width: fit-content;">
            <a style="padding: 10px;margin: 40px;z-index: 1;position: relative;" class="btn btn-secondary dropdown-toggle" href="#" role="button"
                id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user.username}}
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/users/account/">Mon compte</a></li>
                <li><a class="dropdown-item" href="/users/logout/">Déconnexion</a></li>
            </ul>
        </div>
    </div>
    {% endif %}

        {% if messages %}

        <div class="messages">
            {% for message in messages %}

            <div {% if message.tags %} class=" {{ message.tags }} " {% endif %} role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}

    <div class="wrapper">
        {% block wrapper %} {% endblock %}
    </div>

</body>

</html>

templates/channel_modify.html
{% extends "base.html" %}
{% load static %}
{% block title %}Modifier le salon {{ channel.name }}{% endblock %}
{% block wrapper %}
<h1>Modifier le salon</h1><br/>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="channel_name">Nom du salon :</label><div class="input-box">
    <input type="text" name="name" value="{{ channel.name }}" autofocus required id="channel_name"></div>

    <button type="submit" class="btn">Valider les modifications</button>

</form>

<br/><div class="link"><p><a href="{% url 'options-channel' slug=channel.id %}">Retour</a></p></div>
{% endblock %}

templates/channel_options.html
{% extends "base.html" %}
{% load static %}
{% block title %}Options du salon {{ channel.name }}{% endblock %}
{% block wrapper %}
<h1>Options du salon</h1><br />


Nom du salon : {{channel.name}}         
{% if is_moderator %}
<div class="link" style="display: inline;">
    <a href="{% url 'modify-channel' slug=channel.id %}"><button class="btn" style="width: 90px;">Modifier</button></a>
</div>
{% endif %}

<br />
Participants : {{ channel.participants }}
<div class="popover_wrapper">
    <div class="link popover_title" >▼</div>
    <div class="popover_content">
            {% for member in channel.members.all %}
                <p>{{member.username}}</p>
            {% endfor %}
    </div>
  </div>

{% if channel.is_private is not True %} <!-- cant invite to private channel -->
<!-- hidden variable for js, to avoid injections caused by using template language inside script tag -->
<input type="hidden" id="var_invite_url" name="var_invite_url"
    value="{% url 'send-invite' channel_id=channel.id user_to_add=None %}">

<div class="link">

    <div class="input-box">
        <label for="invite_input">Invitations :</label>
        <input type="text" style="width: 300px;" id="invite_input" placeholder="username or email address">
        <button type="submit" style="width:80px;" id="invite_button" class="btn"
            onclick="gen_invite_url()">Inviter</button>
    </div>

</div>



{% if is_moderator %}
<form method="POST" action="{% url 'change-user-role' channel_id=channel.id %}">
    {% csrf_token %}
    <div class="input-box">
        <label for="user_select">Sélectionner un utilisateur :</label>
        <select name="user" class="btn" id="user_select" style="width: fit-content;">
            {% for member in channel.members.all %}
                <option style="color:black;" value="{{ member.id }}">{{ member.username }}</option>
            {% endfor %}
        </select>
        <label for="role_input">Changer le rôle :</label>
        <select name="role" id="role_input" class="btn" style="width: fit-content;">
            <option style="color:black;" value="moderator">Modérateur</option>
            <option style="color:black;" value="member">Membre</option>
        </select>
        <button type="submit" style="width:90px;" id="role_button" class="btn">Modifier</button>
    </div>
    <br>
    <br>
</form>

{% endif %}
{% if is_creator %}
        <div class="link">
            <p><a href="{% url 'delete-channel' slug=channel.id %}">Supprimer le salon</a></p>
        </div>
{% endif %}
{% endif %}
</br>
<div class="link">
    <p><a href="{% url 'show-channel' slug=channel.id %}">Retour</a></p>
</div>


<script>
    function gen_invite_url() {
        //timeout the button to avoid spam

        var invite_button = document.getElementById("invite_button");
        //disable
        invite_button.disabled = true;
        invite_button.style.opacity = '0.5';
        //re enable after timeout
        setTimeout(function () {
            invite_button.disabled = false;
            invite_button.style.opacity = 1;
        }, 500); // 1.5 seconds



        var userInput = document.getElementById('invite_input').value;
        var baseURL = document.getElementById('var_invite_url').value;

        fetch(baseURL.replace('None', userInput))
            .then(response => {

                var existingUl = document.querySelector('.messages');

                
                var ulElement = existingUl || document.createElement('div');
                ulElement.className = 'messages';

                
                var divElement = document.createElement('div');
                if (response.status === 200) {
                    divElement.className = 'alert alert-success alert-dismissible fade show';
                } else {
                    divElement.className = 'alert alert-warning alert-dismissible fade show';
                }
                divElement.setAttribute('role', 'alert');
                divElement.textContent = response.headers.get('content-type');

                
                var closeButton = document.createElement('button');
                closeButton.type = 'button';
                closeButton.className = 'btn-close';
                closeButton.setAttribute('data-bs-dismiss', 'alert');
                closeButton.setAttribute('aria-label', 'Close');

                
                divElement.appendChild(closeButton);

                
                ulElement.appendChild(divElement);

                if (!existingUl) { // si aucun message avant
                    document.body.appendChild(ulElement);
                }
            })

            .catch(error => {
                console.error('Error during the request:', error);
            });
    }
</script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Nexus Login{% endblock %}
{% block wrapper %}
    <form method="post" action="{% url 'login-view' %}">
        {% csrf_token %}
        <h1>Log in</h1>
        <div class="input-box">
            <input type="text" name="username" placeholder="Username" required>
            <i class='bx bxs-user'></i>
        </div>
        <div class="input-box">
            <input type="password" name="password" placeholder="Password" required>
            <i class='bx bxs-lock-alt'></i>
        </div>

        <div class="remember-forgot">
            <label><input name="remember_me" type="checkbox">Remember me</label>
            <a href="{% url 'reset_password'%}">Forgot password</a>
        </div>

        <button type="submit" class="btn">Login</button>

        <div class="register-link">
            <p>Don't have an account ? <a href="{% url 'signup-view'%}">Register</a></p>
        </div>
    </form>
{% endblock %}

templates/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password reset complete{% endblock %}
{% block wrapper %}

<h1>Password reset complete</h1>
<br>
<h3 style="text-align: center;">Your Password has been set. You may now go ahead and login</h3>
<div class="register-link">
  <form method="get" action="{% url 'login-view' %}">
  <input type="submit" class="btn" value="Goto login page">
</form>

</div>

{% endblock%}

templates/password_reset_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password reset form{% endblock %}
{% block wrapper %}

<form method="post" action="">
    {% csrf_token %}
    <h1>Set your new password</h1>

    {{ form.non_field_errors }}
    {% for field in form %}
    <br>
    {% if field.errors %}<div class="field_error" style="font-weight: bold;">{{ field.errors|striptags }}</div>{% endif %}
    {% if field.help_text %}
        <p class="help_text">{{ field.help_text|safe }}</p>
    {% endif %}
    {% endfor %}
    <div class="input-box">
        <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="New Password">
        <i class="bx bxs-lock-alt"></i>
    </div>

    <div class="input-box">
        <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="New password confirmation">
        <i class="bx bxs-lock-alt"></i>
    </div>

    

    <button type="submit" class="btn">Reset Password</button>
</form>

<script src="{% static  '/js/remove_labels.js'%}"></script>
{% endblock %}

templates/password_reset_sent.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password reset sent{% endblock %}
{% block wrapper %}

<h1>Password Reset Notification</h1>
<br>
<h3 style="text-align: center;">We have sent you an email with instructions on how to reset your password. If there is an account associated with the email you provided, you should receive the instructions shortly.</h3>
<br>
<h4 style="text-align: center;">If you do not receive the email, please double-check that you entered the correct email address during registration and also review your spam folder.</h4>
<div class="register-link">
  <p>
    <a href="{% url 'nexus-hello-view' %}">Return to the home page</a>
  </p>
</div>

{% endblock%}

templates/reset_password.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset{% endblock %}
{% block wrapper %}

<h1>Reset your password</h1>


<br>
<h3 style="text-align: center;">Lost your password in the digital labyrinth? No stress! Give us your sign-up email, and we'll zap over a link to magically revive your access. </h3>
<br>

<form action="" method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
  {% if field.errors %}<div class="field_error" style="font-weight: bold;">{{ field.errors|striptags }}</div>{% endif %}

  <div class="input-box">
    {{ field.label_tag }} {{ field }}
    <i class='bx bxs-user'></i>
    </div>
  {% endfor %}
  <input type="submit" class="btn" value="Send email" /><br>
</form>
<div class="register-link">
  <p>
    <a href="{% url 'nexus-hello-view' %}">Return to home page</a>
  </p>
</div>
<script src="{% static  '/js/remove_labels.js'%}"></script>
{% endblock%}

templates/send_invite.html
{% extends "base.html" %}
{% load static %}
{% block title %}Send invite for {{ channel.name }}{% endblock %}
{% block wrapper %}
<h1>Envoyer une invitation</h1><br/>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="id_username">Username :</label><div class="input-box">
    <input type="text" name="username" autofocus required id="id_username"></div>

    <button type="submit" class="btn">Envoyer l'invitation</button>

</form>

<br/><div class="link"><p><a href="{% url 'options-channel' slug=channel.id %}">Retour</a></p></div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Nexus Sign up{% endblock %}
{% block wrapper %}
<form method="post" action="{% url 'signup-view' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Sign up</h1>

    {{ form.non_field_errors }}
    {% for field in form %}
    {% if field.errors %}<div class="field_error" style="font-weight: bold;">{{ field.errors|striptags }}</div>{% endif %}
    <div class="input-box">
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    
    <button type="submit" class="btn">Sign up</button>
    <div class="register-link">
        <p>Already a member ? <a href="{% url 'login-view' %}">Login</a></p>
    </div>
</form>

<script src="{% static  '/js/remove_labels.js'%}"></script>
{% endblock %}

templates/verify.html
{% extends "base.html" %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static  '/styles/style_verify.css'%}">
{% endblock %}
{% block title %}verify account{% endblock %}
{% block wrapper %}
    <div>
        <h1>
            Thanks!
        </h1>

        <h2>
            Now check your email
        </h2>
    </div>
{% endblock %}